# v1.3.2
---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: PMM                        | Clean YUM cache
      command: /usr/bin/yum --enablerepo=pmm clean all
      changed_when: False

    - name: PMM                        | Backup configuration
      command: /usr/share/pmm-update/helpers/backup-password

    - name: PMM                        | Backup unmanaged configs
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '/etc/orchestrator.conf.json',    dest: '/tmp/orchestrator.conf.json-backup' }
        - { src: '/etc/cron.daily/purge-qan-data', dest: '/tmp/purge-qan-data-backup' }

    - name: PMM                        | Install RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=present enablerepo=pmm
      with_items:
        - nginx
        - pmm-update
        - percona-toolkit-3.0.4
        - percona-dashboards-1.3.2
        - pmm-server-1.3.2
        - percona-orchestrator-2.1.5
        - percona-prometheus-1.7.1
        - percona-node_exporter-0.13.0
        - percona-qan-api-1.3.2
        - percona-grafana-4.4.3
        - percona-qan-app-1.3.2
        - pmm-manage-1.3.2
        - pmm-managed-1.3.2
        - percona-consul-0.8.5

    - name: PMM                        | Remove RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=absent
      with_items:
        - percona-qan-app2

    - name: PMM                        | Restore unmanaged configs
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: '/tmp/orchestrator.conf.json-backup', dest: '/etc/orchestrator.conf.json' }
        - { src: '/tmp/purge-qan-data-backup',         dest: '/etc/cron.daily/purge-qan-data' }

    - name: PMM                        | Remove temporary files
      command: /usr/bin/shred --remove /tmp/orchestrator.conf.json-backup /tmp/purge-qan-data-backup

    - name: PMM                        | Restore configuration
      command: bash -c "/usr/bin/pmm-configure -grafana-db-path $(ls /srv/grafana/grafana.db /var/lib/grafana/grafana.db 2>/dev/null)"

    - name: PMM                        | Stat supervisor
      stat: path=/usr/bin/supervisorctl
      register: supervisorctl

    - name: NGINX                      | Disable daemon
      when: supervisorctl.stat.exists
      lineinfile:
        dest: /etc/nginx/nginx.conf
        line: 'daemon off;'

    - name: NGINX                      | Disable password-page
      when: supervisorctl.stat.exists
      replace:
        dest: /etc/nginx/conf.d/pmm.conf
        regexp: '/usr/share/pmm-server/password-page'
        replace: '/usr/share/pmm-server/landing-page'

    - name: NGINX                      | Fix nginx config
      replace:
        dest: /etc/nginx/nginx.conf
        regexp: '^(\s*)listen'
        replace: '\1#listen'

    - name: PMM                        | Import dashboards
      command: bash -c "/usr/share/percona-dashboards/import-dashboards.py $(dirname $(ls /srv/grafana/grafana.db /var/lib/grafana/grafana.db 2>/dev/null))"
      register: import_result
      changed_when: "'up-to-date' not in import_result.stdout"

    - name: Security                   | Stat sshd_config
      stat: path=/etc/ssh/sshd_config
      register: sshd_config

    - name: Security                   | Disable root SSH access
      when: sshd_config.stat.exists
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Security                   | Remove percona key
      lineinfile:
        dest: /root/.ssh/authorized_keys
        regexp: '([Pp]acker|[Mm]ykola|[Pp]ercona)'
        state: absent

    - name: Security                   | Remove centos user
      when: keep_centos_user is not defined
      user:
        name: centos
        state: absent
        remove: yes

    - name: Hotfix                     | PMM-1232 Fix prometheus memory
      when: supervisorctl.stat.exists
      replace:
        dest: /etc/supervisord.d/pmm.ini
        regexp: '-storage.local.target-heap-size=268435456$'
        replace: '-storage.local.target-heap-size=766957568'

    - name: PMM                        | Prometheus METRICS_RESOLUTION
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/1s/${METRICS_RESOLUTION:-1s}/" /etc/prometheus.yml'

    - name: PMM                        | Prometheus METRICS_RETENTION
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/ENV_METRICS_RETENTION/${METRICS_RETENTION:-720h}/" /etc/supervisord.d/pmm.ini'

    - name: PMM                        | Prometheus METRICS_MEMORY
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/ENV_METRICS_MEMORY_MULTIPLIED/$(( ${METRICS_MEMORY:-748982} * 1024 ))/" /etc/supervisord.d/pmm.ini'

    - name: PMM                        | Orchestrator enabled
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/autostart = false/autostart = ${ORCHESTRATOR_ENABLED:-false}/" /etc/supervisord.d/pmm.ini'

    - name: PMM                        | Orchestrator ORCHESTRATOR_USER
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/orc_client_user/${ORCHESTRATOR_USER:-orc_client_user}/" /etc/orchestrator.conf.json'

    - name: PMM                        | Orchestrator ORCHESTRATOR_PASSWORD
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/orc_client_password/${ORCHESTRATOR_PASSWORD:-orc_client_password}/" /etc/orchestrator.conf.json'

    - name: PMM                        | Cron QUERIES_RETENTION
      when: supervisorctl.stat.exists and image_creation is not defined
      command: sh -c 'sed -i "s/^INTERVAL=.*/INTERVAL=${QUERIES_RETENTION:-8}/" /etc/cron.daily/purge-qan-data'

    - name: PMM                        | Reload config (supervisord)
      when: supervisorctl.stat.exists
      command: /usr/bin/supervisorctl update

    - name: PMM                        | Restart services (supervisord)
      when: supervisorctl.stat.exists
      command: /usr/bin/supervisorctl restart {{ item }}
      with_items:
        - orchestrator
        - prometheus
        - node_exporter
        - qan-api
        - grafana
        - consul
        - pmm-managed

    - name: PMM                        | Restart services (systemd)
      when: not supervisorctl.stat.exists
      service: name={{ item }} state=restarted
      with_items:
        - orchestrator
        - prometheus
        - node_exporter
        - percona-qan-api
        - grafana-server
        - consul
        - pmm-managed
        - sshd

    - name: PMM                        | Restart pmm-manage daemon (delayed)
      shell: cd /tmp; nohup sh -c 'sleep 60; test -e /usr/bin/supervisorctl && /usr/bin/supervisorctl restart pmm-manage nginx || /bin/systemctl restart pmm-manage nginx' </dev/null >/dev/null 2>&1 &
