#!/usr/bin/env bash

set -eu

PMM_DIR=${PMM_DIR:-/usr/local/percona/pmm2}

PMM_USER=${PMM_USER:-}
PMM_GROUP=${PMM_GROUP:-}

if [ -z "${PMM_USER}" -o -z "${PMM_GROUP}" ]; then
    INSTALL_COMMAND="install"
else
    INSTALL_COMMAND="install -o ${PMM_USER} -g ${PMM_GROUP}"
fi

echo "Installing into ${PMM_DIR}..."

${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/bin
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/exporters
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/config
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/textfile-collector
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/textfile-collector/low-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/textfile-collector/medium-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/textfile-collector/high-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/mysql
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/mysql/low-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/mysql/medium-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/mysql/high-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/postgresql
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/postgresql/low-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/postgresql/medium-resolution
${INSTALL_COMMAND} -m 0755 -d ${PMM_DIR}/collectors/custom-queries/postgresql/high-resolution

for FILE in $( ls ${PWD}/bin ); do
    if [ "x${FILE}" = "xpmm-admin" -o "x${FILE}" = "xpmm-agent" ]; then
        ${INSTALL_COMMAND} -m 0755 ${PWD}/bin/${FILE} ${PMM_DIR}/bin
    else
        ${INSTALL_COMMAND} -m 0755 ${PWD}/bin/${FILE} ${PMM_DIR}/exporters
    fi
done
for FILE in example.prom queries-mysqld.yml queries-postgres.yml; do
    for RESOLUTION in low medium high; do
        if [ "x${FILE}" = "xexample.prom" ]; then
            ${INSTALL_COMMAND} -m 0755 ${FILE} ${PMM_DIR}/collectors/textfile-collector/${RESOLUTION}-resolution
        elif [ "x${FILE}" = "xqueries-mysqld.yml" ]; then
            ${INSTALL_COMMAND} -m 0755 ${FILE} ${PMM_DIR}/collectors/custom-queries/mysql/${RESOLUTION}-resolution
        elif [ "x${FILE}" = "xqueries-postgres.yml" ]; then
            ${INSTALL_COMMAND} -m 0755 ${FILE} ${PMM_DIR}/collectors/custom-queries/postgresql/${RESOLUTION}-resolution
        fi
    done
done

${INSTALL_COMMAND} -m 0640 /dev/null ${PMM_DIR}/config/pmm-agent.yaml
