# This workflow will do a clean install of node dependencies and run lint tests

name: Temp test

on:
  pull_request:

jobs:
  trigger:

    runs-on: ubuntu-18.04

    steps:
      - name: Trigger  dispatch
        if: ${{ always() }}
        run: |
          curl -v -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GH_API_TOKEN }}" \
          "https://api.github.com/repos/percona/pmm-qa/actions/workflows/testsuite.yml/dispatches" \
          -d '{"ref":"PMM-7_Migrate_Testsuite","inputs":{"pmm_qa_branch":"PMM-7_Migrate_Testsuite","sha": "${{ github.event.pull_request.head.sha }}" } }'
