name: pmm2-testsuite pipeline
on:
  # run with default inputs
  workflow_dispatch:
    inputs:
      server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      client_version:
        description: "pmm2-client version Tarball or Dev-latest, default is dev-latest"
        required: false
        type: string
      client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string
  workflow_call:
    inputs:
      server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      client_version:
        description: "pmm2-client version Tarball or Dev-latest, default is dev-latest"
        required: false
        type: string
      client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

jobs:
  bats-testsuite:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    env:
      SERVER_IMAGE: ${{ github.event.inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      CLIENT_IMAGE: ${{ github.event.inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      CLIENT_VERSION: ${{ github.event.inputs.client_version || 'dev-latest' }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PMM_QA_BRANCH: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
      DOCKER_VERSION: ${{ github.event.inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      CLIENT_DOCKER_VERSION: ${{ github.event.inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      SHA: ${{ github.event.inputs.sha || 'null' }}
    strategy:
      fail-fast: false
      matrix:
        db-type: [ps5.7, ps8, pdpgsql13, pdpgsql14, pdpgsql15, modb4.4, modb5, modb6, generic, clientContainer, haproxy, proxysql, ms8.0]

    steps:
      - name: Checkout PMM-QA tests when Workflow_dispatch
        if: ${{ github.event_name == 'workflow_call' || github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PMM_QA_BRANCH }}
          repository: percona/pmm-qa
          path: ./
      - name: Checkout PMM-QA tests when pull_request
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3
        with:
          path: ./

      - name: Setup tools
        run: |
          npm install -g bats
          sudo apt-get install -y apt-transport-https ca-certificates dirmngr ansible libaio1 libaio-dev libnuma-dev libncurses5 socat sysbench
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
          echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee \
              /etc/apt/sources.list.d/clickhouse.list
          sudo apt-get update
          sudo apt-get install -y clickhouse-client
          sudo curl -s https://raw.githubusercontent.com/datacharmer/dbdeployer/master/scripts/dbdeployer-install.sh | bash
          wget https://raw.githubusercontent.com/Percona-QA/percona-qa/master/get_download_link.sh
          chmod +x get_download_link.sh

      - name: Setup PMM2-Server
        run: |
          docker create -v /srv --name pmm-server-data ${{ env.SERVER_IMAGE }}
          docker run -d -p 80:80 -p 443:443 -p 9000:9000 -e PERCONA_TEST_PLATFORM_ADDRESS=https://check-dev.percona.com:443 -e PERCONA_TEST_PLATFORM_PUBLIC_KEY=RWTg+ZmCCjt7O8eWeAmTLAqW+1ozUbpRSKSwNTmO+exlS5KEIPYWuYdX --volumes-from pmm-server-data --name pmm-server --restart always ${{ env.SERVER_IMAGE }}
          sleep 30

      - name: Setup PMM2-Client
        run: sudo bash -x ./pmm-tests/pmm2-client-setup.sh --pmm_server_ip 127.0.0.1 --client_version ${{ env.CLIENT_VERSION }} --admin_password admin --use_metrics_mode no

      - name: Run Setup for ps5.7
        if: ${{ matrix.db-type == 'ps5.7' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=ps,1 --ps-version=5.7 --pmm2

      - name: Run Setup for ps8.0
        if: ${{ matrix.db-type == 'ps8' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=ps,1 --ps-version=8 --pmm2

      - name: Run bats tests for PS
        if: ${{ matrix.db-type == 'ps5.7' || matrix.db-type == 'ps8' }}
        run: sudo bats ./pmm-tests/pmm-2-0-bats-tests/ps-specific-tests.bats

      - name: Run Setup for pdpgsql 13
        if: ${{ matrix.db-type == 'pdpgsql13' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=pdpgsql,1 --pdpgsql-version=13 --pmm2

      - name: Run Setup for pdpgsql 14
        if: ${{ matrix.db-type == 'pdpgsql14' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=pdpgsql,1 --pdpgsql-version=14 --pmm2

      - name: Run Setup for pdpgsql 15.0
        if: ${{ matrix.db-type == 'pdpgsql15' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=pdpgsql,1 --pdpgsql-version=15.0 --pmm2

      - name: Run bats tests for PDPGSQL
        if: ${{ matrix.db-type == 'pdpgsql13' || matrix.db-type == 'pdpgsql14' || matrix.db-type == 'pdpgsql15' }}
        run: |
          sudo bats ./pmm-tests/pmm-2-0-bats-tests/pdpgsql-tests.bats
          sudo bats ./pmm-tests/pmm-2-0-bats-tests/pgsql-specific-tests.bats

      - name: Run Setup for PSMDB 4.4
        if: ${{ matrix.db-type == 'modb4.4' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=modb,1 --modb-version=4.4 --pmm2

      - name: Run Setup for PSMDB 5
        if: ${{ matrix.db-type == 'modb5' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=modb,1 --modb-version=5 --pmm2

      - name: Run Setup for PSMDB 6
        if: ${{ matrix.db-type == 'modb6' }}
        run: sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=modb,1 --modb-version=6 --pmm2

      - name: Run bats tests for PSMDB
        if: ${{ matrix.db-type == 'modb6' || matrix.db-type == 'modb5' || matrix.db-type == 'modb4.4' }}
        run: sudo bats ./pmm-tests/pmm-2-0-bats-tests/modb-tests.bats

      - name: Run Setup Generic Tests, Including Client Container Setup
        if: ${{ matrix.db-type == 'clientContainer' }}
        run: |
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bash -x ./pmm-tests/pmm-framework.sh --setup-pmm-client-docker --pmm2

      - name: Run bats tests for generic Scenarios
        if: ${{ matrix.db-type == 'generic' }}
        run: |
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bats ./pmm-tests/pmm-2-0-bats-tests/generic-tests.bats
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bats ./pmm-tests/pmm-2-0-bats-tests/docker-env-variable-tests.bats

      - name: Run bats tests for Client Container Scenarios
        if: ${{ matrix.db-type == 'clientContainer' }}
        run: |
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bats ./pmm-tests/pmm-2-0-bats-tests/pmm-client-docker-tests.bats
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bats ./pmm-tests/pmm-2-0-bats-tests/pmm-admin-unregister-tests.bats

      - name: Run Setup for HAPROXY
        if: ${{ matrix.db-type == 'haproxy' }}
        run: |
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=haproxy,1 --pmm2

      - name: Run bats tests for Client Container Scenarios
        if: ${{ matrix.db-type == 'haproxy' }}
        run: |
          CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bats ./pmm-tests/pmm-2-0-bats-tests/haproxy-tests.bats

      - name: Run Setup for ProxySQL
        if: ${{ matrix.db-type == 'proxysql' }}
        run: CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=pxc,1 --pmm2 --pxc-version=5.7

      - name: Run bats tests for ProxySQL
        if: ${{ matrix.db-type == 'proxysql' }}
        run: |
          sudo bats ./pmm-tests/pmm-2-0-bats-tests/proxysql-specific-tests.bats

      - name: Run Setup for MySQL
        if: ${{ matrix.db-type == 'ms8.0' }}
        run: CLIENT_VERSION=${{ CLIENT_VERSION }} CLIENT_DOCKER_VERSION=${{ CLIENT_DOCKER_VERSION }} sudo bash -x ./pmm-tests/pmm-framework.sh --addclient=ms,1 --pmm2 --ms-version=8.0

      - name: Run bats tests for MySQL Tests
        if: ${{ matrix.db-type == 'ms8.0' }}
        run: |
          sudo bats ./pmm-tests/pmm-2-0-bats-tests/ms-specific-tests.bats
      - name: Create status check
        if: ${{ always() }}
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          SHA: ${{ inputs.sha }}
          STATUS: ${{ job.status }}
          JOB_ID: ${{ job.id }}
        run: |
          result="${{ needs.build.result }}"
          if [ "${STATUS}" = "cancelled" ]; then
            STATUS="error"
          fi
          gh api \
            --method POST \
            -H "Accept: application/vnd.github.v3+json" \
            /repos/$REPO/statuses/$SHA \
            -f state="$STATUS" \
            -f target_url="https://github.com/$REPO/actions/runs/$RUN_ID" \
            -f description="pmm2-testsuite bats cli tests ${{ matrix.db-type }} $STATUS" \
            -f context='actions/workflows/bats-testsuite/${{ matrix.db-type }}'
