name: pmm2-ui-tests-fb pipeline
on:
  # run with default inputs
  pull_request:
  workflow_dispatch:
    inputs:
      server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      client_version:
        description: "pmm2-client version Tarball or Dev-latest, default is dev-latest"
        required: false
        type: string
      client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      pmm_ui_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string
  workflow_call:
    inputs:
      server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      client_version:
        description: "pmm2-client version Tarball or Dev-latest, default is dev-latest"
        required: false
        type: string
      client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      pmm_ui_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

jobs:
  env:
    SERVER_IMAGE: ${{ github.event.inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
    CLIENT_IMAGE: ${{ github.event.inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
    CLIENT_VERSION: ${{ github.event.inputs.client_version || 'dev-latest' }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    ADMIN_PASSWORD: ${{ github.event.inputs.admin_password || 'admin-password' }}
    PMM_QA_BRANCH: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
    PMM_QA_GIT_BRANCH: ${{ github.event.inputs.pmm_qa_branch || 'main' }}
    PMM_UI_BRANCH: ${{ github.event.inputs.pmm_ui_branch || 'main' }}
    DOCKER_VERSION: ${{ github.event.inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
    CLIENT_DOCKER_VERSION: ${{ github.event.inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
    SHA: ${{ github.event.inputs.sha || 'null' }}

  ui-tests-stt:
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/workflows/ui-tests.yml
      with:
        server_image: ${{ env.SERVER_IMAGE }}
        client_version: ${{ env.CLIENT_VERSION }}
        client_image: ${{ env.CLIENT_IMAGE }}
        pmm_qa_branch: ${{ env.PMM_QA_BRANCH }}
        pmm_ui_branch: ${{ env.PMM_UI_BRANCH }}
        sha: ${{ env.SHA }}
        client_flags: '--addclient=ps,1 --ps-version=5.7.30'
        tags_for_tests: '@stt'
