name: pmm2-ui-tests-fb pipeline
on:

  workflow_dispatch:
    inputs:
      server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      client_version:
        description: "pmm2-client version Tarball or Dev-latest, default is dev-latest"
        required: false
        type: string
      client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      pmm_ui_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

  workflow_call:
    inputs:
      server_image:
        description: "pmm-server docker image, default perconalab/pmm-server:dev-latest"
        required: false
        type: string
      client_version:
        description: "pmm2-client version Tarball URL or Dev-latest, default is dev-latest"
        required: false
        type: string
      client_image:
        description: "pmm2-client docker image, default perconalab/pmm-client:dev-latest"
        required: false
        type: string
      pmm_qa_branch:
        description: "Branch for PMM-QA to checkout"
        required: false
        type: string
      pmm_ui_branch:
        description: "Branch for PMM-UI tests to checkout"
        required: false
        type: string
      sha:
        description: "SHA (leave empty if running manually, default - 'null')"
        required: false
        type: string

    secrets:
      BACKUP_LOCATION_ACCESS_KEY:
        required: false
      BACKUP_LOCATION_SECRET_KEY:
        required: false


jobs:
  advisors:
      name: Advisors UI tests
      uses: ./.github/workflows/ui-tests.yml
      secrets: inherit
      with:
        server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
        client_version: ${{ inputs.client_version || 'dev-latest' }}
        client_image: ${{ inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
        pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
        pmm_ui_branch: ${{ inputs.pmm_ui_branch || 'main' }}
        sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
        client_flags: '--addclient=ps,1 --ps-version=5.7.30'
        tags_for_tests: '@advisors-fb'

  backup_management:
    name: Backup Management UI tests
    uses: ./.github/workflows/ui-tests.yml
    secrets: inherit
    with:
      server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      client_version: ${{ inputs.client_version || 'dev-latest' }}
      client_image: ${{ inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_ui_branch: ${{ inputs.pmm_ui_branch || 'main' }}
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      client_flags: '--mongo-replica-for-backup'
      tags_for_tests: '@bm-fb'

  instances:
    name: Instances UI tests
    uses: ./.github/workflows/ui-tests.yml
    secrets: inherit
    with:
      server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      client_version: ${{ inputs.client_version || 'dev-latest' }}
      client_image: ${{ inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_ui_branch: ${{ inputs.pmm_ui_branch || 'main' }}
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      client_flags: '--addclient=haproxy,1 --addclient=ps,1 --setup-external-service'
      tags_for_tests: '@instances-fb'

  alerting_and_settings:
    name: Alerting and Settings UI tests
    uses: ./.github/workflows/ui-tests.yml
    secrets: inherit
    with:
      server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      client_version: ${{ inputs.client_version || 'dev-latest' }}
      client_image: ${{ inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_ui_branch: ${{ inputs.pmm_ui_branch || 'main' }}
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      tags_for_tests: '@alerting-fb|@settings-fb'

  user_and_password:
    name: User with changed password UI tests
    uses: ./.github/workflows/ui-tests.yml
    secrets: inherit
    with:
      server_image: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      client_version: ${{ inputs.client_version || 'dev-latest' }}
      client_image: ${{ inputs.client_image || 'perconalab/pmm-client:dev-latest' }}
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
      pmm_ui_branch: ${{ inputs.pmm_ui_branch || 'main' }}
      sha: ${{ inputs.sha || github.event.pull_request.head.sha ||  'null' }}
      client_flags: '--addclient=ps,1 --addclient=modb,1 --addclient=pdpgsql,1'
      tags_for_tests: '@user-password'

  rbac:
    name: RBAC UI tests
    uses: percona/pmm-ui-tests/.github/workflows/pmm-ui-tests.yml@PMM-11616-matrix-pipelines
    secrets: inherit
    with:
      pmm_ui_tests_branch: ${{ inputs.pmm_ui_branch || 'main '}}
      pmm_test_flag: '@rbac'
      pmm_server_version: 'dev-latest'
      pmm_server_docker_tag: ${{ inputs.server_image || 'perconalab/pmm-server:dev-latest' }}
      pmm_client_version: ${{ inputs.client_version || 'dev-latest' }}
      pmm_clients: '--addclient=ps,1'
      pmm_qa_branch: ${{ inputs.pmm_qa_branch || 'main' }}
