name: PR Checks

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - ready_for_review
      - synchronize

  workflow_dispatch:

jobs:
  fb_tests:
    if: ${{ github.event.pull_request.draft == false && contains(github.event.pull_request.labels.*.name, 'build') }}
    uses: ./.github/workflows/pmm-qa-fb-checks.yml
    secrets: inherit
    with:
      sha: ${{ github.event.pull_request.head.sha }}

